// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEwW9TzGpikQW9FnfqSbah3AG_L4c_Mvo',
    appId: '1:700811312802:web:97bd9139843acae8eae1fb',
    messagingSenderId: '700811312802',
    projectId: 'auth-48b22',
    authDomain: 'auth-48b22.firebaseapp.com',
    storageBucket: 'auth-48b22.firebasestorage.app',
    measurementId: 'G-Z76C6R72H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIY4-EDlOAHp84Oy_bFXvFrdc2jQusI3o',
    appId: '1:700811312802:android:b727d44d551bdfe5eae1fb',
    messagingSenderId: '700811312802',
    projectId: 'auth-48b22',
    storageBucket: 'auth-48b22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiqBnIJPHa8ltL0zS5tzmEAe66YTdiyIs',
    appId: '1:700811312802:ios:35a285e7349231cceae1fb',
    messagingSenderId: '700811312802',
    projectId: 'auth-48b22',
    storageBucket: 'auth-48b22.firebasestorage.app',
    iosClientId: '700811312802-0png63i3bpj92qqaqjp0m50lpjt800cb.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartcook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiqBnIJPHa8ltL0zS5tzmEAe66YTdiyIs',
    appId: '1:700811312802:ios:35a285e7349231cceae1fb',
    messagingSenderId: '700811312802',
    projectId: 'auth-48b22',
    storageBucket: 'auth-48b22.firebasestorage.app',
    iosClientId: '700811312802-0png63i3bpj92qqaqjp0m50lpjt800cb.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartcook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEwW9TzGpikQW9FnfqSbah3AG_L4c_Mvo',
    appId: '1:700811312802:web:e45133b9106cd7d0eae1fb',
    messagingSenderId: '700811312802',
    projectId: 'auth-48b22',
    authDomain: 'auth-48b22.firebaseapp.com',
    storageBucket: 'auth-48b22.firebasestorage.app',
    measurementId: 'G-CL1DSNZ6GC',
  );
}
